# Generated by Django 3.1.1 on 2020-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
